name: wordle
description: "Wordle clone made with Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  provider: ^6.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.24.9
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
